using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using InterknotCalculator.Generators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace InterknotCalculator.Generators;

[Generator]
public class AgentRegistryGenerator : IIncrementalGenerator {
    private const string AgentFqn          = "InterknotCalculator.Core.Classes.Agents.Agent";
    private static readonly Regex MindscapeSuffix = new(@"M(\d+)$", RegexOptions.Compiled);
    
    private static INamedTypeSymbol FindAnchor(INamedTypeSymbol variant) {
        // Walk up until parent is abstract; the last concrete class on the way is the anchor.
        var current = variant;
        while (current.BaseType is { IsAbstract: false } parent)
            current = parent;
        return current; // its parent is abstract → it's the anchor
    }

    private static bool ImplementsReference(INamedTypeSymbol type) =>
        type.AllInterfaces.Any(i =>
            i.IsGenericType &&
            i.ConstructedFrom.MetadataName == "IAgentReference`1" &&
            i.ContainingNamespace?.ToDisplayString() == "InterknotCalculator.Core.Interfaces");
    
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var classes = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
            transform: (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)
        ).Where(s => s is not null);

        var agents = classes.Collect();
        
        context.RegisterSourceOutput(agents, (spc, all) => {
            // Every concrete class derived (transitively) from Agent.
            var concreteAgents = all
                .Where(s => s is INamedTypeSymbol { IsAbstract: false } sym && sym.InheritsFrom(AgentFqn))
                .Select(s => s!)
                .ToImmutableArray();

            // Anchors: parent class is abstract (Agent itself, or RuptureAgent, etc.).
            var anchors = concreteAgents
                .Where(s => s is INamedTypeSymbol { BaseType.IsAbstract: true })
                .ToImmutableArray();

            // Variants: parent is a non-abstract class derived from Agent.
            // Group them under the anchor they ultimately descend from.
            var variantsByAnchor = concreteAgents
                .Where(s => s is INamedTypeSymbol { BaseType.IsAbstract: false })
                .Cast<INamedTypeSymbol>()
                .GroupBy(FindAnchor, SymbolEqualityComparer.Default)
                .ToDictionary(g => g.Key!, g => g.ToArray(),
                              SymbolEqualityComparer.Default);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            // sb.AppendLine("using InterknotCalculator.Core.Classes.Server;");
            sb.AppendLine("namespace InterknotCalculator.Core.Classes.Agents;");
            sb.AppendLine();
            sb.AppendLine("public static partial class AgentRegistry {");
            sb.AppendLine("    static AgentRegistry() {");

            foreach (var anchor in anchors.OrderBy(a => a.Name)) {
                var anchorFqn = anchor.ToDisplayString();

                // Read the Id from a temporary instance of the anchor.
                sb.AppendLine("        {");
                sb.AppendLine($"            var anchor = new {anchorFqn}();");

                if (variantsByAnchor.TryGetValue(anchor, out var variants) && variants.Length > 0) {
                    var ordered = variants
                        .Select(v => (Fqn: v.ToDisplayString(),
                                      Match: MindscapeSuffix.Match(v.Name)))
                        .Where(x => x.Match.Success)
                        .Select(x => (x.Fqn, Level: int.Parse(x.Match.Groups[1].Value)))
                        .OrderBy(x => x.Level)
                        .ToArray();

                    sb.AppendLine("            Instances[anchor.Id] = mindscape => mindscape switch {");
                    sb.AppendLine($"                0 => new {anchorFqn}(),");
                    foreach (var v in ordered)
                        sb.AppendLine($"                {v.Level} => new {v.Fqn}(),");
                    sb.AppendLine("                _ => throw new System.ArgumentOutOfRangeException(");
                    sb.AppendLine($"                    nameof(mindscape), mindscape, \"Invalid mindscape for {anchor.Name}.\")");
                    sb.AppendLine("            };");
                } else {
                    sb.AppendLine($"            Instances[anchor.Id] = _ => new {anchorFqn}();");
                }

                if (anchor is INamedTypeSymbol anc && ImplementsReference(anc))
                    sb.AppendLine($"            References[anchor.Id] = static (weaponId, setId) => {anchorFqn}.Reference(weaponId, setId);");

                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("AgentRegistry.g.cs", sb.ToString());
        });

    }
}