using System.Collections.Immutable;
using System.Linq;
using System.Text;
using InterknotCalculator.Generators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace InterknotCalculator.Generators;

[Generator]
public class DriveDiscSetRegistryGenerator : IIncrementalGenerator {
    private const string DriveDiscSetFqn = "InterknotCalculator.Core.Classes.DriveDiscSets.DriveDiscSet";
    
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var classes = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
            transform: (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)
        ).Where(s => s is not null);

        var weapons = classes.Collect();
        
        context.RegisterSourceOutput(weapons, (spc, all) => {
            var concreteSets = all
                .Where(s => s is INamedTypeSymbol { IsAbstract: false } sym && sym.InheritsFrom(DriveDiscSetFqn))
                .Select(s => s!)
                .ToImmutableArray();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace InterknotCalculator.Core.Classes.DriveDiscSets;");
            sb.AppendLine();
            sb.AppendLine("public static partial class DriveDiscSetRegistry {");
            sb.AppendLine("    static DriveDiscSetRegistry() {");

            foreach (var sym in concreteSets.OrderBy(a => a.Name)) {
                var ddsFqn = sym.ToDisplayString();
                sb.AppendLine("        {");
                sb.AppendLine($"            var dds = new {ddsFqn}();");
                sb.AppendLine($"            Instances[dds.Id] = static () => new {ddsFqn}();");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            spc.AddSource("DriveDiscSetRegistry.g.cs", sb.ToString());
        });
    }
}