using System.Collections.Immutable;
using System.Linq;
using System.Text;
using InterknotCalculator.Generators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace InterknotCalculator.Generators;

[Generator]
public class WeaponRegistryGenerator : IIncrementalGenerator {
    private const string WeaponFqn = "InterknotCalculator.Core.Classes.Weapons.Weapon";
    
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var classes = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
            transform: (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)
        ).Where(s => s is not null);

        var weapons = classes.Collect();
        
        context.RegisterSourceOutput(weapons, (spc, all) => {
            var concreteWeapons = all
                .Where(s => s is INamedTypeSymbol { IsAbstract: false } sym && sym.InheritsFrom(WeaponFqn))
                .Select(s => s!)
                .ToImmutableArray();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            // sb.AppendLine("using InterknotCalculator.Core.Classes.Weapons;");
            sb.AppendLine("namespace InterknotCalculator.Core.Classes.Weapons;");
            sb.AppendLine();
            sb.AppendLine("public static partial class WeaponRegistry {");
            sb.AppendLine("    static WeaponRegistry() {");

            foreach (var sym in concreteWeapons.OrderBy(a => a.Name)) {
                var weaponFqn = sym.ToDisplayString();
                sb.AppendLine("        {");
                sb.AppendLine($"            var weapon = new {weaponFqn}();");
                sb.AppendLine($"            Instances[weapon.Id] = static () => new {weaponFqn}();");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            spc.AddSource("WeaponRegistry.g.cs", sb.ToString());
        });
    }
}